namespace JoakimAnder.Toolbox.SourceGenerators.DependencyInjection.Emit;

internal static class AttributeSource
{
    public const string HintName = "JoakimAnder.Toolbox.DependencyInjection.Attributes.g.cs";

    public const string SingletonMetadataName = "JoakimAnder.Toolbox.DependencyInjection.SingletonAttribute";
    public const string ScopedMetadataName = "JoakimAnder.Toolbox.DependencyInjection.ScopedAttribute";
    public const string TransientMetadataName = "JoakimAnder.Toolbox.DependencyInjection.TransientAttribute";

    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace JoakimAnder.Toolbox.DependencyInjection
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class SingletonAttribute : global::System.Attribute
            {
                public SingletonAttribute(global::System.Type? serviceType = null) => ServiceType = serviceType;
                public global::System.Type? ServiceType { get; }
                public string? Group { get; set; }
                public string? Key { get; set; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class ScopedAttribute : global::System.Attribute
            {
                public ScopedAttribute(global::System.Type? serviceType = null) => ServiceType = serviceType;
                public global::System.Type? ServiceType { get; }
                public string? Group { get; set; }
                public string? Key { get; set; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class TransientAttribute : global::System.Attribute
            {
                public TransientAttribute(global::System.Type? serviceType = null) => ServiceType = serviceType;
                public global::System.Type? ServiceType { get; }
                public string? Group { get; set; }
                public string? Key { get; set; }
            }
        }
        """;
}
