using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using JoakimAnder.Toolbox.SourceGenerators.DependencyInjection.Model;
using Microsoft.CodeAnalysis.CSharp;

namespace JoakimAnder.Toolbox.SourceGenerators.DependencyInjection.Emit;

internal static class RegistrationEmitter
{
    public const string HintName = "AttributedServices.g.cs";

    public static string Emit(IReadOnlyList<ServiceRegistration> registrations)
    {
        var sorted = registrations
            .OrderBy(r => r.Group ?? "", StringComparer.Ordinal)
            .ThenBy(r => r.ImplementationType, StringComparer.Ordinal)
            .ThenBy(r => r.ServiceType ?? "", StringComparer.Ordinal)
            .ThenBy(r => r.Key ?? "", StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("namespace JoakimAnder.Toolbox.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    internal static partial class AttributedServiceCollectionExtensions");
        sb.AppendLine("    {");

        var groups = sorted
            .GroupBy(r => r.Group ?? "")
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        for (var i = 0; i < groups.Count; i++)
        {
            if (i > 0) sb.AppendLine();
            var methodName = "AddAttributed" + groups[i].Key + "Services";
            sb.AppendLine($"        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}(");
            sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("        {");
            foreach (var reg in groups[i])
                sb.AppendLine("            " + Line(reg));
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Line(ServiceRegistration reg)
    {
        var method = reg.Lifetime switch
        {
            Lifetime.Singleton => reg.Key is null ? "AddSingleton" : "AddKeyedSingleton",
            Lifetime.Scoped => reg.Key is null ? "AddScoped" : "AddKeyedScoped",
            _ => reg.Key is null ? "AddTransient" : "AddKeyedTransient",
        };

        var typeArgs = reg.ServiceType is null
            ? $"<{reg.ImplementationType}>"
            : $"<{reg.ServiceType}, {reg.ImplementationType}>";

        var args = reg.Key is null ? "" : SymbolDisplay.FormatLiteral(reg.Key, quote: true);

        return $"services.{method}{typeArgs}({args});";
    }
}
